# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           pci-ids
Version:        0.2.5
Release:        %autorelease
Summary:        Rust wrappers for the PCI ID Repository

License:        MIT
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/lienching/pci-ids.rs
Source:         %{url}/archive/refs/tags/v%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Rust wrappers for the PCI ID Repository.}

%description %{_description}

%prep
%autosetup -n pci-ids-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md

%changelog
%autochangelog
